image: maven:3.9.6-eclipse-temurin-21

stages:
  - build
  - test

before_script:
  - echo "Setting up environment"
  - apt-get update -qq && apt-get install -y openjdk-21-jdk

build:
  stage: build
  script:
    - mvn clean compile

test:
  stage: test
  script:
    - mvn test